# Generated by Django 3.2.5 on 2021-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_albums_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
