# Generated by Django 3.2.5 on 2021-08-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_albums_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='logo_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
