# Generated by Django 3.2.5 on 2021-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_albums_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
