# Generated by Django 3.2.5 on 2021-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20210818_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.FloatField(null=True),
        ),
    ]
