# Generated by Django 3.2.5 on 2021-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_alter_song_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.FileField(upload_to='media/%y'),
        ),
    ]
