# Generated by Django 3.2.5 on 2021-08-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='LocalUsers',
        ),
    ]
